// Pre-match / interaction conversations between Overwatch heroes, sourced
// verbatim from overwatch.fandom.com along with the per-line voice line
// audio file the wiki links for each turn. Generated by
// scripts/build-quote-audio.mjs into data/quote-conversations.json. Both
// Quote mode (text reveal) and any future audio-enabled twists pull from
// here so dialogue and recordings stay in lockstep.

import data from "@/data/quote-conversations.json";

export type ConversationLine = {
  // 0 = first speaker, 1 = second speaker.
  speaker: 0 | 1;
  text: string;
  // Public-relative URL to the per-line voice clip
  // (e.g. /voicelines/quote/hanzo_-_how_would_you_know.mp3). Always present
  // for wiki-sourced conversations; only entries with full per-line audio
  // make it into the manifest.
  audio: string;
};

export type Conversation = {
  speakers: [string, string]; // hero keys; index matches `speaker` on each line
  context?: string; // optional setting label, e.g. "Pre-match"
  lines: ConversationLine[];
};

export const CONVERSATIONS: Conversation[] = data as Conversation[];
