-- Generated by scripts/migrate-deadlockle-votes.mjs
-- Source: deadlockle-votes
-- Rows:   1
-- Apply with:
--   wrangler d1 execute owdle-votes --remote --file=db/migration-import-deadlockle.sql

INSERT INTO votes (game_id, voter_hash, game_name, game_image, game_released, created_at, source) VALUES ('324997', '3bb15e91c0964e57e2ae20be752b50bc856da4592957cb2c3419549aec44eb8f', 'Baldur''s Gate III', 'https://media.rawg.io/media/games/699/69907ecf13f172e9e144069769c3be73.jpg', '2023-08-03', 1778218255, 'deadlockle') ON CONFLICT(game_id, voter_hash) DO NOTHING;
