-- Run once against the canonical D1 (owdle-votes):
--   wrangler d1 execute owdle-votes --remote --file=db/migration-add-source.sql
--
-- Adds the `source` column the shared schema requires. Existing rows in
-- owdle-votes are backfilled to source='owdle' via the column default.
-- Deadlockle rows are imported afterwards with source='deadlockle'
-- explicitly via db/migration-import-deadlockle.sql (generated by
-- scripts/migrate-deadlockle-votes.mjs).

ALTER TABLE votes ADD COLUMN source TEXT NOT NULL DEFAULT 'owdle';
CREATE INDEX IF NOT EXISTS idx_votes_source ON votes(source);
